platform :ios, "6.0"

pod 'MJRefresh', '~> 2.2.1'
#pod 'HBFastTableViewController', :podspec => 'https://github.com/Natoto/HBFastTableViewCotroller/blob/master/HBFastTableViewController.podspec'
#target :Tests, :exclusive => true do
# pod 'Kiwi'
#end