platform :ios, "7.0"
#pod 'HBFastTable', :git => 'https://github.com/Natoto/HBFastTableViewCotroller.git'
pod 'MJRefresh', '~> 2.4.8'
pod 'AFNetworking-ReactiveCocoa', '~> 0.0.2'
#pod 'ReactiveCocoa', '~> 3.0.0-alpha.1'
#use_frameworks!
#pod 'Alamofire', '~> 2.0.0-beta.3' 

#pod "<#PodName#>"
#target :<#TargetName#>Tests, :exclusive => true do
  # pod 'Kiwi'
#end